export const ESCROW_ABI = [
  'error Unauthorized()',
  'error InvalidInput()',
  'error InvalidRole()',
  'error AlreadyRegistered()',
  'error NotRegistered()',
  'error InvalidStatus()',
  'error InvalidMilestone()',
  'error DeadlinePassed()',
  'error DeadlineNotPassed()',
  'error TransferFailed()',
  'error ReentrantCall()',
  'error AgreementNotFound(uint256 agreementId)',
  'error InvalidCarrier(address carrier)',
  'error SameParticipant()',
  'error EmptyTitle()',
  'error ZeroFunding()',
  'error InvalidDeadline(uint64 provided,uint64 currentTime)',
  'error InvalidMilestoneCount(uint256 count)',
  'error MilestoneArrayLengthMismatch()',
  'error EmptyMilestoneName(uint256 milestoneIndex)',
  'error ZeroMilestonePayout(uint256 milestoneIndex)',
  'error MilestoneDeadlineNotSequential(uint256 milestoneIndex)',
  'error MilestoneDeadlineAfterAgreement(uint256 milestoneIndex)',
  'error PayoutTotalMismatch(uint256 payoutTotal,uint256 depositedAmount)',
  'error InputTooLong(uint256 providedLength,uint256 maximumLength)',
  'error InvalidProofURI()',
  'error DeadlineRefundAvailable()',
  'error DuplicateAgreementName()',
  'error FixedMilestonesRequired()',
  'error InvalidMilestonePayout(uint256 milestoneIndex,uint256 expectedPayout,uint256 providedPayout)',
  'error EvidenceMissing()',
  'error EvidenceHashMismatch(bytes32 storedHash,bytes32 suppliedHash)',
  'error PaymentAlreadyReleased()',
  'function arbitrator() view returns (address)',
  'function CONTRACT_VERSION() view returns (uint256)',
  'function EVIDENCE_URI_SCHEME() view returns (string)',
  'function MAX_MILESTONES() view returns (uint256)',
  'function PICKUP_PAYMENT_PERCENT() view returns (uint256)',
  'function REPUTATION_POINTS_PER_MILESTONE() view returns (uint256)',
  'function MAX_PROFILE_NAME_LENGTH() view returns (uint256)',
  'function MAX_AGREEMENT_TITLE_LENGTH() view returns (uint256)',
  'function MAX_AGREEMENT_NOTES_LENGTH() view returns (uint256)',
  'function MAX_MILESTONE_NAME_LENGTH() view returns (uint256)',
  'function MAX_MILESTONE_DETAILS_LENGTH() view returns (uint256)',
  'function MAX_PROOF_URI_LENGTH() view returns (uint256)',
  'function MAX_DISPUTE_REASON_LENGTH() view returns (uint256)',
  'function agreementCount() view returns (uint256)',
  'function carrierReputation(address carrier) view returns (uint256)',
  'function register(string name, uint8 role)',
  'function getProfile(address account) view returns (tuple(string name,uint8 role,uint64 registeredAt))',
  'function getUsersByRole(uint8 role) view returns (address[])',
  'function createAgreement(string title,address carrier,uint64 deadline,string notes,string[] milestoneNames,string[] milestoneDetails,uint256[] payouts,uint64[] dueDates) payable returns (uint256)',
  'function isAgreementNameAvailable(address shipper,string title) view returns (bool)',
  'function submitEvidence(uint256 agreementId,uint256 milestoneIndex,bytes32 evidenceHash)',
  'function submitMilestoneProof(uint256 agreementId,uint256 milestoneIndex,bytes32 proofHash,string proofURI)',
  'function confirmMilestone(uint256 agreementId,uint256 milestoneIndex,bytes32 expectedEvidenceHash)',
  'function approveMilestone(uint256 agreementId,uint256 milestoneIndex)',
  'function claimRefundAfterDeadline(uint256 agreementId)',
  'function openDispute(uint256 agreementId,string reason)',
  'function resolveDispute(uint256 agreementId,uint256 shipperAmount)',
  'function getAgreement(uint256 agreementId) view returns (tuple(address shipper,address carrier,string title,string notes,uint256 totalAmount,uint256 remainingAmount,uint64 deadline,uint64 createdAt,uint8 status,uint32 nextMilestone))',
  'function getMilestones(uint256 agreementId) view returns (tuple(string name,string details,uint256 payout,uint64 dueAt,bytes32 proofHash,string proofURI,uint64 submittedAt,uint64 approvedAt,uint8 state,bool paid)[])',
  'function getUserAgreementIds(address account) view returns (uint256[])',
  'function canRefund(uint256 agreementId) view returns (bool)',
  'event UserRegistered(address indexed account,uint8 indexed role,string name)',
  'event AgreementCreated(uint256 indexed agreementId,address indexed shipper,address indexed carrier,uint256 amount,uint64 deadline)',
  'event MilestoneProofSubmitted(uint256 indexed agreementId,uint256 indexed milestoneIndex,bytes32 indexed proofHash,string proofURI)',
  'event MilestoneApproved(uint256 indexed agreementId,uint256 indexed milestoneIndex,uint256 payout)',
  'event MilestoneConfirmed(uint256 indexed agreementId,uint256 indexed milestoneIndex,bytes32 indexed evidenceHash,address confirmer,uint256 paymentAmount)',
  'event CarrierReputationAwarded(address indexed carrier,uint256 indexed agreementId,uint256 indexed milestoneIndex,uint256 points,uint256 totalPoints)',
  'event AgreementCompleted(uint256 indexed agreementId)',
  'event Refunded(uint256 indexed agreementId,address indexed shipper,uint256 amount)',
  'event DisputeOpened(uint256 indexed agreementId,address indexed openedBy,string reason)',
  'event DisputeResolved(uint256 indexed agreementId,uint256 shipperAmount,uint256 carrierAmount)',
];

export const ROLE_LABELS = ['Unregistered', 'Shipper', 'Carrier'];
export const AGREEMENT_STATUS = ['Active', 'Completed', 'Refunded', 'Disputed', 'Resolved'];
export const MILESTONE_STATUS = ['Pending', 'Evidence submitted', 'Confirmed & paid'];
