export const ESCROW_ABI = [
  'error Unauthorized()',
  'error InvalidInput()',
  'error InvalidRole()',
  'error AlreadyRegistered()',
  'error NotRegistered()',
  'error InvalidStatus()',
  'error InvalidMilestone()',
  'error DeadlinePassed()',
  'error DeadlineNotPassed()',
  'error TransferFailed()',
  'error ReentrantCall()',
  'error AgreementNotFound(uint256 agreementId)',
  'error InvalidCarrier(address carrier)',
  'error SameParticipant()',
  'error EmptyTitle()',
  'error ZeroFunding()',
  'error InvalidDeadline(uint64 provided,uint64 currentTime)',
  'error InvalidMilestoneCount(uint256 count)',
  'error MilestoneArrayLengthMismatch()',
  'error EmptyMilestoneName(uint256 milestoneIndex)',
  'error ZeroMilestonePayout(uint256 milestoneIndex)',
  'error MilestoneDeadlineNotSequential(uint256 milestoneIndex)',
  'error MilestoneDeadlineAfterAgreement(uint256 milestoneIndex)',
  'error PayoutTotalMismatch(uint256 payoutTotal,uint256 depositedAmount)',
  'error InputTooLong(uint256 providedLength,uint256 maximumLength)',
  'error InvalidProofURI()',
  'error DeadlineRefundAvailable()',
  'error DisputeNotAvailableBeforeFinalDeadline(uint64 availableAt)',
  'error DuplicateAgreementName()',
  'error FixedMilestonesRequired()',
  'error EvidenceMissing()',
  'error EvidenceHashMismatch(bytes32 storedHash,bytes32 suppliedHash)',
  'error PaymentAlreadyReleased()',
  'error ReviewPeriodActive(uint64 availableAt)',
  'error ExtensionRequestTooEarly(uint64 availableAt)',
  'error ExtensionRequestClosed()',
  'error ExtensionAlreadyRequested()',
  'error InvalidExtensionDeadline(uint64 proposedDeadline,uint64 maximumDeadline)',
  'error NoPendingExtension()',
  'function arbitrator() view returns (address)',
  'function CONTRACT_VERSION() view returns (uint256)',
  'function EVIDENCE_URI_SCHEME() view returns (string)',
  'function MAX_MILESTONES() view returns (uint256)',
  'function REPUTATION_POINTS_PER_MILESTONE() view returns (uint256)',
  'function EVIDENCE_REVIEW_PERIOD() view returns (uint256)',
  'function EXTENSION_REQUEST_WINDOW() view returns (uint256)',
  'function EXTENSION_DURATION() view returns (uint256)',
  'function EXTENSION_COMPENSATION_BPS() view returns (uint256)',
  'function MAX_PROFILE_NAME_LENGTH() view returns (uint256)',
  'function MAX_AGREEMENT_TITLE_LENGTH() view returns (uint256)',
  'function MAX_AGREEMENT_NOTES_LENGTH() view returns (uint256)',
  'function MAX_MILESTONE_NAME_LENGTH() view returns (uint256)',
  'function MAX_MILESTONE_DETAILS_LENGTH() view returns (uint256)',
  'function MAX_PROOF_URI_LENGTH() view returns (uint256)',
  'function MAX_DISPUTE_REASON_LENGTH() view returns (uint256)',
  'function agreementCount() view returns (uint256)',
  'function carrierReputation(address carrier) view returns (uint256)',
  'function register(string name, uint8 role)',
  'function getProfile(address account) view returns (tuple(string name,uint8 role,uint64 registeredAt))',
  'function getUsersByRole(uint8 role) view returns (address[])',
  'function createAgreement(string title,address carrier,uint64 deadline,string notes,string[] milestoneNames,string[] milestoneDetails,uint256[] payouts,uint64[] dueDates) payable returns (uint256)',
  'function isAgreementNameAvailable(address shipper,string title) view returns (bool)',
  'function submitEvidence(uint256 agreementId,uint256 milestoneIndex,bytes32 evidenceHash)',
  'function submitMilestoneProof(uint256 agreementId,uint256 milestoneIndex,bytes32 proofHash,string proofURI)',
  'function confirmMilestone(uint256 agreementId,uint256 milestoneIndex,bytes32 expectedEvidenceHash)',
  'function approveMilestone(uint256 agreementId,uint256 milestoneIndex)',
  'function rejectEvidence(uint256 agreementId,uint256 milestoneIndex)',
  'function requestDeadlineExtension(uint256 agreementId,uint256 milestoneIndex,string reason)',
  'function approveDeadlineExtension(uint256 agreementId,uint256 milestoneIndex)',
  'function rejectDeadlineExtension(uint256 agreementId,uint256 milestoneIndex)',
  'function getExtensionRequest(uint256 agreementId,uint256 milestoneIndex) view returns (uint64 requestedAt,uint64 proposedDueAt,uint256 compensation,bool requested,bool pending,bool approved,string reason)',
  'function requestArbitrationAfterReviewTimeout(uint256 agreementId,uint256 milestoneIndex)',
  'function claimRefundAfterDeadline(uint256 agreementId)',
  'function openDispute(uint256 agreementId,string reason)',
  'function resolveDispute(uint256 agreementId,uint256 shipperAmount)',
  'function getAgreement(uint256 agreementId) view returns (tuple(address shipper,address carrier,string title,string notes,uint256 totalAmount,uint256 remainingAmount,uint64 deadline,uint64 createdAt,uint8 status,uint32 nextMilestone))',
  'function getMilestones(uint256 agreementId) view returns (tuple(string name,string details,uint256 payout,uint64 dueAt,bytes32 proofHash,string proofURI,uint64 submittedAt,uint64 approvedAt,uint8 state,bool paid,uint64 extensionRequestedAt,uint64 extensionProposedDueAt,uint256 extensionCompensation,bool extensionRequested,bool extensionPending,bool extensionApproved)[])',
  'function getUserAgreementIds(address account) view returns (uint256[])',
  'function canRefund(uint256 agreementId) view returns (bool)',
  'event UserRegistered(address indexed account,uint8 indexed role,string name)',
  'event AgreementCreated(uint256 indexed agreementId,address indexed shipper,address indexed carrier,uint256 amount,uint64 deadline)',
  'event MilestoneProofSubmitted(uint256 indexed agreementId,uint256 indexed milestoneIndex,bytes32 indexed proofHash,string proofURI)',
  'event MilestoneApproved(uint256 indexed agreementId,uint256 indexed milestoneIndex,uint256 payout)',
  'event MilestoneConfirmed(uint256 indexed agreementId,uint256 indexed milestoneIndex,bytes32 indexed evidenceHash,address confirmer,uint256 paymentAmount)',
  'event CarrierReputationAwarded(address indexed carrier,uint256 indexed agreementId,uint256 indexed milestoneIndex,uint256 points,uint256 totalPoints)',
  'event EvidenceRejected(uint256 indexed agreementId,uint256 indexed milestoneIndex,address indexed shipper,uint256 refundAmount)',
  'event AgreementCompleted(uint256 indexed agreementId)',
  'event Refunded(uint256 indexed agreementId,address indexed shipper,uint256 amount)',
  'event DisputeOpened(uint256 indexed agreementId,address indexed openedBy,string reason)',
  'event ArbitrationRequested(uint256 indexed agreementId,uint256 indexed milestoneIndex,address indexed carrier)',
  'event DeadlineExtensionRequested(uint256 indexed agreementId,uint256 indexed milestoneIndex,address indexed carrier,uint64 proposedDueAt,string reason)',
  'event DeadlineExtensionApproved(uint256 indexed agreementId,uint256 indexed milestoneIndex,uint64 newDueAt,uint256 compensation)',
  'event DeadlineExtensionRejected(uint256 indexed agreementId,uint256 indexed milestoneIndex)',
  'event ExtensionCompensationPaid(uint256 indexed agreementId,uint256 indexed milestoneIndex,address indexed shipper,uint256 amount)',
  'event DisputeResolved(uint256 indexed agreementId,uint256 shipperAmount,uint256 carrierAmount)',
];

export const ROLE_LABELS = ['Unregistered', 'Shipper', 'Carrier', 'Arbitrator'];
export const AGREEMENT_STATUS = ['Active', 'Completed', 'Refunded', 'Disputed', 'Resolved'];
export const MILESTONE_STATUS = ['Pending', 'Evidence submitted', 'Confirmed & paid'];
